### ISSUE TITLE
Could not pass event PlayerJoinEvent to HideItem v3.0.3

### ISSUE THREAD

**Issue by Lerbiq** [1vomarek1/HideItem#3]
When loading the server this error message appears:

`
[08:17:36 ERROR]: Could not pass event PlayerJoinEvent to HideItem v3.0.3
java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.Arrays$ArrayList.set(Arrays.java:3846) ~[?:1.8.0_242]
at net.minecraft.server.v1_15_R1.NonNullList.set(SourceFile:53) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerInventory.setItem(PlayerInventory.java:448) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:64) ~[patched_1.15.2.jar:git-Paper-371]
at com.vomarek.hideitem.events.EventsClass.PlayerJoin(EventsClass.java:166) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-371]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-371]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
`

I haven't had an opportunity to test if the player hiding actually works or not.

**Comment by 1vomarek1** [comment]
Can I see your config.yml?

**Comment by Lerbiq** [comment]
Sure. I didnt make any changes to the default config tho.
https://pastelink.net/1rhcv

**Comment by 1vomarek1** [comment]
Try this jar
http://i.vomarek.com/HideItem/jars/HideItem-3.0.3.jar

**Comment by 1vomarek1** [comment]
fixed in 6049dce
