### ISSUE TITLE
Error when interacting with pressure plates

### ISSUE THREAD

**Issue by 1vomarek1** [1vomarek1/HideItem#4]
`[09:08:52 ERROR]: Could not pass event PlayerInteractEvent to HideItem v3.0.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[event.jar:git-Paper-33d42c8e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[event.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[event.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[event.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[event.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:1015) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:596) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:645) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[event.jar:git-Paper-33d42c8e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:862) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[event.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[event.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at com.vomarek.hideitem.events.EventsClass.onClick(EventsClass.java:39) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[event.jar:git-Paper-33d42c8e]
        ... 22 more`

**Comment by 1vomarek1** [comment]
Fixed in 6049dce
